coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true

ignore:
  - "tests/**"
  - "docs/**"
  - "scripts/**"
  - "extensions/**"
